# Generated by Django 4.0 on 2022-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weeklytop3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=128)),
                ('top_name', models.CharField(max_length=128)),
                ('top_salesAmt', models.BigIntegerField()),
                ('top_audiCnt', models.BigIntegerField()),
                ('second_name', models.CharField(max_length=128)),
                ('second_salesAmt', models.BigIntegerField()),
                ('second_audiCnt', models.BigIntegerField()),
                ('third_name', models.CharField(max_length=128)),
                ('third_salesAmt', models.BigIntegerField()),
                ('third_audiCnt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'weeklytop3',
            },
        ),
    ]
