# Generated by Django 4.0 on 2022-01-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('readcount', models.IntegerField()),
                ('writedate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('upload_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment_user', models.CharField(max_length=200)),
                ('comment_content', models.TextField()),
                ('board_id', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.board')),
            ],
        ),
    ]
