# Generated by Django 3.2.9 on 2021-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('movieNm', models.CharField(max_length=200)),
                ('openDT', models.CharField(max_length=200)),
                ('salesAmt', models.CharField(max_length=200)),
                ('salesAcc', models.CharField(max_length=200)),
                ('audiCnt', models.CharField(max_length=200)),
                ('audiAcc', models.CharField(max_length=200)),
            ],
        ),
    ]
