# Generated by Django 3.2.9 on 2022-01-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insertcnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('sysdate', models.DateField(auto_now=True)),
                ('systime', models.TimeField(auto_now='sysdate')),
            ],
        ),
        migrations.CreateModel( 
            name='insertcntrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='totalrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('rank', models.IntegerField(null=True)),
                ('sysdate', models.DateField(null=True)),
            ],
        ),
    ]
