# Generated by Django 3.2.9 on 2022-01-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertcnt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insertcntrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='totalrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('rank', models.IntegerField(null=True)),
                ('sysdate', models.DateField(null=True)),
            ],
        ),
    ]
