# Generated by Django 3.2.9 on 2022-01-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertcnt', '0002_insertcntrank_totalrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertcntrank',
            name='text',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='totalrank',
            name='sysdate',
            field=models.TextField(null=True),
        ),
    ]
