# Generated by Django 3.2.9 on 2022-01-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('otteid', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(null=True)),
                ('collection_id', models.IntegerField(null=True)),
                ('collection_name', models.CharField(max_length=10, null=True)),
                ('themovieid', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=10, null=True)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('original_title', models.CharField(max_length=300)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('poster_path', models.CharField(max_length=100, null=True)),
                ('release_date', models.CharField(max_length=10, null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('naverid', models.IntegerField(null=True)),
                ('naverscore', models.FloatField(null=True)),
                ('imdbscore', models.FloatField(null=True)),
                ('ottescore', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movieactors',
            fields=[
                ('maid', models.AutoField(primary_key=True, serialize=False)),
                ('ottepersonid', models.IntegerField()),
                ('themovieid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='moviedirectors',
            fields=[
                ('mdid', models.AutoField(primary_key=True, serialize=False)),
                ('ottepersonid', models.IntegerField()),
                ('themovieid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='moviegenres',
            fields=[
                ('combineid', models.AutoField(primary_key=True, serialize=False)),
                ('otteid', models.IntegerField()),
                ('genreid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('ottepersonid', models.AutoField(primary_key=True, serialize=False)),
                ('themovieid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
