# Generated by Django 3.2.9 on 2022-01-12 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0003_auto_20220110_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseasons',
            name='otteid',
        ),
        migrations.AlterField(
            model_name='moviegenres',
            name='genreid',
            field=models.ForeignKey(db_column='gnereid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themovieDB.genresinmovie'),
        ),
        migrations.DeleteModel(
            name='TV',
        ),
        migrations.DeleteModel(
            name='TVseasons',
        ),
    ]
