# Generated by Django 3.2.9 on 2022-01-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0004_auto_20220112_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moviegenres',
        ),
    ]
