# Generated by Django 3.2.9 on 2022-01-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0005_delete_moviegenres'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviegenres',
            fields=[
                ('combineid', models.AutoField(primary_key=True, serialize=False)),
                ('otteid', models.IntegerField()),
                ('genreid', models.ForeignKey(db_column='gnereid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themovieDB.genresinmovie')),
            ],
        ),
    ]
