# Generated by Django 3.2.9 on 2022-01-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0006_moviegenres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenres',
            name='genreid',
            field=models.ForeignKey(db_column='genreid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themovieDB.genresinmovie'),
        ),
    ]
