# Generated by Django 3.2.9 on 2022-01-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0007_alter_moviegenres_genreid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieactors',
            name='ottepersonid',
        ),
        migrations.RemoveField(
            model_name='movieactors',
            name='themovieid',
        ),
        migrations.RemoveField(
            model_name='moviedirectors',
            name='ottepersonid',
        ),
        migrations.RemoveField(
            model_name='moviedirectors',
            name='themovieid',
        ),
        migrations.AddField(
            model_name='movieactors',
            name='otteid',
            field=models.ForeignKey(db_column='otteid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themovieDB.movie'),
        ),
        migrations.AddField(
            model_name='movieactors',
            name='personname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moviedirectors',
            name='otteeid',
            field=models.ForeignKey(db_column='otteid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themovieDB.movie'),
        ),
        migrations.AddField(
            model_name='moviedirectors',
            name='personname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
