# Generated by Django 3.2.9 on 2022-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0009_rename_otteeid_moviedirectors_otteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactors',
            name='otteid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedirectors',
            name='otteid',
            field=models.IntegerField(null=True),
        ),
    ]
