# Generated by Django 3.2.9 on 2022-02-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0010_auto_20220113_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieott',
            fields=[
                ('moid', models.AutoField(primary_key=True, serialize=False)),
                ('ottename', models.CharField(max_length=10, null=True)),
                ('otteid', models.IntegerField(null=True)),
            ],
        ),
    ]
