# Generated by Django 3.2.9 on 2022-02-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0011_movieott'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieott',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
