# Generated by Django 3.2.9 on 2022-02-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0012_movieott_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieott',
            old_name='ottename',
            new_name='ottname',
        ),
    ]
