# Generated by Django 3.2.9 on 2022-02-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewnumber',
            field=models.IntegerField(null=True),
        ),
    ]
