# Generated by Django 3.2.9 on 2022-02-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0017_remove_review_reviewnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='otteid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='themovieDB.movie'),
            preserve_default=False,
        ),
    ]
